import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./componenets/Navbar/Navbar";
import Footer from "./componenets/footer/Footer";
import SessionWrapper from "@/SessionWrapper/SessionWrapper";
import { Toaster } from "@/components/ui/toaster";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}:Readonly<{children: React.ReactNode;}>) {
  return (
    <SessionWrapper>
      <html lang="en">
      <body className="font-work flex flex-col min-h-screen bg-white">
        <Navbar/>
        {children}
      
        <Toaster/>
        <Footer/>
        </body>
    </html>
    </SessionWrapper>
    
  );
}
